figs =
# figs += model.risk
# figs += model.hiv
# figs += model.cascade
# figs += model.wp.adj
# figs += binom.dur
# figs += binom.waste
# figs += binom.wph
# figs += binom.bph
# figs += dots.wph
# figs += dots.bph
# figs += binom.dots.xph
all:
	for fig in $(figs); do \
	  ./maketikz.sh $$fig ;\
	done