figs =
# figs += model.risk
# figs += model.hiv
# figs += model.hiv.p
# figs += model.cascade
# figs += model.wp.adj
# figs += binom.dur
# figs += binom.waste
# figs += binom.wph
# figs += binom.bph
# figs += dots.wph
# figs += dots.bph
# figs += binom.dots.xph
# figs += foi.toy.freq
# figs += foi.toy.pair
# figs += esw.timeline
# figs += durs.partner
# figs += durs.pop
# figs += durs.tte
# figs += mf.comp
# figs += mf.pair
# figs += mf.ibm
all:
	for fig in $(figs); do \
	  ./maketikz.sh $$fig ;\
	done
