figs =
figs += model.risk
figs += model.hiv
figs += model.hiv.fpe
figs += model.smdm
figs += binom.lin
figs += binom.mod
figs += model.cascade
figs += model.wp.adj
figs += tx.pairs
figs += tx.freq
all:
	for fig in $(figs); do \
	  ./maketikz.sh $$fig ;\
	done